---
- name: install defined version of Home Assistant
  pip:
    name: homeassistant
    version: "{{ homeassistant__version }}"
    executable: pip3
  when: homeassistant__version != 'latest'

- name: install latest version of Home Assistant
  pip:
    name: homeassistant
    extra_args: --upgrade
    executable: pip3
  when: homeassistant__version == 'latest'
