---
- name: add python3
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - python3-dev
    - python3-pip

- command: pip3 install --upgrade virtualenv

- name: install required python modules (pre-install)
  pip: 
    name: "{{ item }}"
    extra_args: "--upgrade" 
    executable: pip3
  with_items:
    - colorlog
