---
- name: install systemd service file
  template:
    src: templates/systemd.service.j2
    dest: "/etc/systemd/system/home-assistant.service"
    owner: root
    group: root
    mode: 0644
  notify:
     - start home assistant